utils: convert collected as a Set artifacts into List
This fixes introduced by previous commit issue:
```
hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: java.util.LinkedHashSet.add() is applicable for argument types: (java.lang.Integer, java.lang.String) values: [0, metal]
```