jenkins/plugins: add the cloudbees-disk-usage-simple plugin
This plugin is a dependency of the Prometheus plugin from the base
OpenShift Jenkins image, since it has collectDiskUsage enabled by
default. Without this plugin, we're getting a warning in the logs
roughly every 2 minutes:

  Cannot collect disk usage data because plugin CloudBees Disk Usage
  Simple is not installed: java.lang.NoClassDefFoundError:
  com/cloudbees/simplediskusage/QuickDiskUsagePlugin

Let's install the plugin so disk usage metrics are actually collected,
and to avoid the added noise in the logs.