rename createCosaRemoteSession -> makeCosaRemoteSession
Apparently Codacy/Codenarc has some arbitrary rules about naming
functions starting with make/create/build and it doesn't like this
function being named create*. Rather than fight it I'll just change
the name and move on to something more important.

```
Error: FactoryMethodName

A factory method is a method that creates objects, and they are
typically named either buildFoo(), makeFoo(), or createFoo().
This rule enforces that only one naming convention is used.
It defaults to allowing makeFoo(), but that can be changed using
the property regex.
```